# Generated by Django 3.2.5 on 2021-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Andhra Pradesh', 'Andhra Pradesh'), ('West Bangal', 'West Bangal'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat')], max_length=50),
        ),
    ]
